import type { Role } from '@/generated/prisma/client'

export const PERMISSIONS = {
  STUDENTS: {
    READ: 'students.read',
    CREATE: 'students.create',
    UPDATE: 'students.update',
    DELETE: 'students.delete',
  },
  STAFF: {
    READ: 'staff.read',
    CREATE: 'staff.create',
    UPDATE: 'staff.update',
    DELETE: 'staff.delete',
  },
  CLASSES: {
    READ: 'classes.read',
    CREATE: 'classes.create',
    UPDATE: 'classes.update',
    DELETE: 'classes.delete',
  },
  SUBJECTS: {
    READ: 'subjects.read',
    CREATE: 'subjects.create',
    UPDATE: 'subjects.update',
    DELETE: 'subjects.delete',
  },
  ATTENDANCE: {
    READ: 'attendance.read',
    WRITE: 'attendance.write',
  },
  EXAMS: {
    READ: 'exams.read',
    CREATE: 'exams.create',
    UPDATE: 'exams.update',
    DELETE: 'exams.delete',
    PUBLISH: 'exams.publish',
  },
  FEES: {
    READ: 'fees.read',
    CREATE: 'fees.create',
    UPDATE: 'fees.update',
    CONFIRM: 'fees.confirm',
  },
  ANNOUNCEMENTS: {
    READ: 'announcements.read',
    CREATE: 'announcements.create',
    DELETE: 'announcements.delete',
  },
  TIMETABLE: {
    READ: 'timetable.read',
    CREATE: 'timetable.create',
    DELETE: 'timetable.delete',
  },
  SETTINGS: {
    READ: 'settings.read',
    UPDATE: 'settings.update',
  },
  ADMISSIONS: {
    READ: 'admissions.read',
    CREATE: 'admissions.create',
    APPROVE: 'admissions.approve',
    REJECT: 'admissions.reject',
  },
  ANALYTICS: {
    READ: 'analytics.read',
  },
  USERS: {
    MANAGE: 'users.manage',
  },
  AUDIT: {
    READ: 'audit.read',
  },
  REPORTS: {
    EXPORT: 'reports.export',
  },
} as const

export type Permission =
  | (typeof PERMISSIONS)['STUDENTS'][keyof (typeof PERMISSIONS)['STUDENTS']]
  | (typeof PERMISSIONS)['STAFF'][keyof (typeof PERMISSIONS)['STAFF']]
  | (typeof PERMISSIONS)['CLASSES'][keyof (typeof PERMISSIONS)['CLASSES']]
  | (typeof PERMISSIONS)['SUBJECTS'][keyof (typeof PERMISSIONS)['SUBJECTS']]
  | (typeof PERMISSIONS)['ATTENDANCE'][keyof (typeof PERMISSIONS)['ATTENDANCE']]
  | (typeof PERMISSIONS)['EXAMS'][keyof (typeof PERMISSIONS)['EXAMS']]
  | (typeof PERMISSIONS)['FEES'][keyof (typeof PERMISSIONS)['FEES']]
  | (typeof PERMISSIONS)['ANNOUNCEMENTS'][keyof (typeof PERMISSIONS)['ANNOUNCEMENTS']]
  | (typeof PERMISSIONS)['TIMETABLE'][keyof (typeof PERMISSIONS)['TIMETABLE']]
  | (typeof PERMISSIONS)['SETTINGS'][keyof (typeof PERMISSIONS)['SETTINGS']]
  | (typeof PERMISSIONS)['ADMISSIONS'][keyof (typeof PERMISSIONS)['ADMISSIONS']]
  | (typeof PERMISSIONS)['ANALYTICS'][keyof (typeof PERMISSIONS)['ANALYTICS']]
  | (typeof PERMISSIONS)['USERS'][keyof (typeof PERMISSIONS)['USERS']]
  | (typeof PERMISSIONS)['AUDIT'][keyof (typeof PERMISSIONS)['AUDIT']]
  | (typeof PERMISSIONS)['REPORTS'][keyof (typeof PERMISSIONS)['REPORTS']]

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPER_ADMIN: [
    PERMISSIONS.STUDENTS.READ,
    PERMISSIONS.STUDENTS.CREATE,
    PERMISSIONS.STUDENTS.UPDATE,
    PERMISSIONS.STUDENTS.DELETE,
    PERMISSIONS.STAFF.READ,
    PERMISSIONS.STAFF.CREATE,
    PERMISSIONS.STAFF.UPDATE,
    PERMISSIONS.STAFF.DELETE,
    PERMISSIONS.CLASSES.READ,
    PERMISSIONS.CLASSES.CREATE,
    PERMISSIONS.CLASSES.UPDATE,
    PERMISSIONS.CLASSES.DELETE,
    PERMISSIONS.SUBJECTS.READ,
    PERMISSIONS.SUBJECTS.CREATE,
    PERMISSIONS.SUBJECTS.UPDATE,
    PERMISSIONS.SUBJECTS.DELETE,
    PERMISSIONS.ATTENDANCE.READ,
    PERMISSIONS.ATTENDANCE.WRITE,
    PERMISSIONS.EXAMS.READ,
    PERMISSIONS.EXAMS.CREATE,
    PERMISSIONS.EXAMS.UPDATE,
    PERMISSIONS.EXAMS.DELETE,
    PERMISSIONS.EXAMS.PUBLISH,
    PERMISSIONS.FEES.READ,
    PERMISSIONS.FEES.CREATE,
    PERMISSIONS.FEES.UPDATE,
    PERMISSIONS.FEES.CONFIRM,
    PERMISSIONS.ANNOUNCEMENTS.READ,
    PERMISSIONS.ANNOUNCEMENTS.CREATE,
    PERMISSIONS.ANNOUNCEMENTS.DELETE,
    PERMISSIONS.TIMETABLE.READ,
    PERMISSIONS.TIMETABLE.CREATE,
    PERMISSIONS.TIMETABLE.DELETE,
    PERMISSIONS.SETTINGS.READ,
    PERMISSIONS.SETTINGS.UPDATE,
    PERMISSIONS.ADMISSIONS.READ,
    PERMISSIONS.ADMISSIONS.CREATE,
    PERMISSIONS.ADMISSIONS.APPROVE,
    PERMISSIONS.ADMISSIONS.REJECT,
    PERMISSIONS.ANALYTICS.READ,
    PERMISSIONS.USERS.MANAGE,
    PERMISSIONS.AUDIT.READ,
    PERMISSIONS.REPORTS.EXPORT,
  ],
  ADMIN: [
    PERMISSIONS.STUDENTS.READ,
    PERMISSIONS.STUDENTS.CREATE,
    PERMISSIONS.STUDENTS.UPDATE,
    PERMISSIONS.STUDENTS.DELETE,
    PERMISSIONS.STAFF.READ,
    PERMISSIONS.STAFF.CREATE,
    PERMISSIONS.STAFF.UPDATE,
    PERMISSIONS.STAFF.DELETE,
    PERMISSIONS.CLASSES.READ,
    PERMISSIONS.CLASSES.CREATE,
    PERMISSIONS.CLASSES.UPDATE,
    PERMISSIONS.CLASSES.DELETE,
    PERMISSIONS.SUBJECTS.READ,
    PERMISSIONS.SUBJECTS.CREATE,
    PERMISSIONS.SUBJECTS.UPDATE,
    PERMISSIONS.SUBJECTS.DELETE,
    PERMISSIONS.ATTENDANCE.READ,
    PERMISSIONS.ATTENDANCE.WRITE,
    PERMISSIONS.EXAMS.READ,
    PERMISSIONS.EXAMS.CREATE,
    PERMISSIONS.EXAMS.UPDATE,
    PERMISSIONS.EXAMS.DELETE,
    PERMISSIONS.EXAMS.PUBLISH,
    PERMISSIONS.FEES.READ,
    PERMISSIONS.FEES.CREATE,
    PERMISSIONS.FEES.UPDATE,
    PERMISSIONS.FEES.CONFIRM,
    PERMISSIONS.ANNOUNCEMENTS.READ,
    PERMISSIONS.ANNOUNCEMENTS.CREATE,
    PERMISSIONS.ANNOUNCEMENTS.DELETE,
    PERMISSIONS.TIMETABLE.READ,
    PERMISSIONS.TIMETABLE.CREATE,
    PERMISSIONS.TIMETABLE.DELETE,
    PERMISSIONS.SETTINGS.READ,
    PERMISSIONS.SETTINGS.UPDATE,
    PERMISSIONS.ADMISSIONS.READ,
    PERMISSIONS.ADMISSIONS.CREATE,
    PERMISSIONS.ADMISSIONS.APPROVE,
    PERMISSIONS.ADMISSIONS.REJECT,
    PERMISSIONS.ANALYTICS.READ,
    PERMISSIONS.REPORTS.EXPORT,
  ],
  TEACHER: [
    PERMISSIONS.STUDENTS.READ,
    PERMISSIONS.CLASSES.READ,
    PERMISSIONS.SUBJECTS.READ,
    PERMISSIONS.ATTENDANCE.READ,
    PERMISSIONS.ATTENDANCE.WRITE,
    PERMISSIONS.EXAMS.READ,
    PERMISSIONS.EXAMS.CREATE,
    PERMISSIONS.EXAMS.UPDATE,
    PERMISSIONS.TIMETABLE.READ,
    PERMISSIONS.ANNOUNCEMENTS.READ,
    PERMISSIONS.ANNOUNCEMENTS.CREATE,
    PERMISSIONS.ANALYTICS.READ,
  ],
  STUDENT: [
    PERMISSIONS.STUDENTS.READ,
    PERMISSIONS.ATTENDANCE.READ,
    PERMISSIONS.EXAMS.READ,
    PERMISSIONS.FEES.READ,
    PERMISSIONS.TIMETABLE.READ,
    PERMISSIONS.ANNOUNCEMENTS.READ,
    PERMISSIONS.SUBJECTS.READ,
  ],
  PARENT: [
    PERMISSIONS.STUDENTS.READ,
    PERMISSIONS.ATTENDANCE.READ,
    PERMISSIONS.EXAMS.READ,
    PERMISSIONS.FEES.READ,
    PERMISSIONS.TIMETABLE.READ,
    PERMISSIONS.ANNOUNCEMENTS.READ,
    PERMISSIONS.SUBJECTS.READ,
  ],
}

export function hasPermission(role: Role, permission: Permission): boolean {
  const perms = ROLE_PERMISSIONS[role]
  if (!perms) return false
  return perms.includes(permission)
}

export function hasAnyPermission(role: Role, ...permissions: Permission[]): boolean {
  return permissions.some((p) => hasPermission(role, p))
}

export function hasAllPermissions(role: Role, ...permissions: Permission[]): boolean {
  return permissions.every((p) => hasPermission(role, p))
}
