import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowLeft, Shield, Clock, KeyRound } from 'lucide-react'

import { requirePage } from '@/lib/permissions'
import { prisma } from '@/lib/db'
import { PageHeader } from '@/components/page-header'
import { Button } from '@/components/ui/button'
import { formatDate } from '@/lib/format'

export const metadata: Metadata = { title: 'Password & Security' }

export default async function SecurityPage() {
  const user = await requirePage('SUPER_ADMIN', 'ADMIN', 'TEACHER', 'STUDENT', 'PARENT')

  const [sessions, recentActivity, passwordResets] = await Promise.all([
    prisma.userSession.findMany({ where: { userId: user.id }, orderBy: { lastActiveAt: 'desc' }, take: 10 }),
    prisma.userActivityLog.findMany({ where: { userId: user.id, action: { in: ['PASSWORD_CHANGED', 'LOGIN', 'PROFILE_UPDATED'] } }, orderBy: { createdAt: 'desc' }, take: 5 }),
    prisma.passwordResetRequest.findMany({ where: { userId: user.id, status: 'PENDING' } }),
  ])

  return (
    <div className="space-y-8 animate-fade-in">
      <PageHeader title="Password & Security" subtitle="Manage your password and security settings">
        <Link href="/profile" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="size-4" /> Back
        </Link>
      </PageHeader>

      <div className="grid gap-6 lg:grid-cols-3">
        <div className="lg:col-span-2 space-y-6">
          <div className="glass-card rounded-2xl overflow-hidden">
            <div className="border-b border-border/50 px-6 py-4">
              <h2 className="text-lg font-semibold tracking-tight">Change Password</h2>
              <p className="text-sm text-muted-foreground mt-0.5">Request a verification PIN from the administrator to change your password</p>
            </div>
            <div className="p-6">
              <p className="text-sm text-muted-foreground mb-4">
                To change your password, you need a 6-digit verification PIN generated by the administrator. Click the button below to request a PIN and proceed.
              </p>
              <Button render={<Link href="/profile/change-password" />}>
                <KeyRound className="size-4 mr-2" /> Change Password
              </Button>
            </div>
          </div>

          <div className="glass-card rounded-2xl overflow-hidden">
            <div className="border-b border-border/50 px-6 py-4">
              <h2 className="text-lg font-semibold tracking-tight">Security Activity</h2>
              <p className="text-sm text-muted-foreground mt-0.5">Recent security-related actions</p>
            </div>
            <div className="p-6">
              {recentActivity.length === 0 ? (
                <p className="text-sm text-muted-foreground text-center py-4">No recent security activity.</p>
              ) : (
                <ul className="space-y-2">
                  {recentActivity.map((a) => (
                    <li key={a.id} className="glass flex items-center justify-between rounded-xl px-4 py-3 text-sm">
                      <div className="flex items-center gap-3">
                        <div className="rounded-lg bg-primary/10 p-2">
                          <Shield className="size-3.5 text-primary" />
                        </div>
                        <div>
                          <p className="font-medium">{a.action.replace(/_/g, ' ').toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase())}</p>
                          <p className="text-xs text-muted-foreground">{a.createdAt.toLocaleDateString()} {a.createdAt.toLocaleTimeString()}</p>
                        </div>
                      </div>
                      <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-semibold ring-1 ring-inset ${a.result === 'success' ? 'bg-emerald-500/10 text-emerald-600 ring-emerald-500/20' : 'bg-red-500/10 text-red-600 ring-red-500/20'}`}>
                        {a.result}
                      </span>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </div>
        </div>

        <div className="space-y-6">
          <div className="glass-card rounded-2xl overflow-hidden">
            <div className="border-b border-border/50 px-6 py-4">
              <h3 className="text-sm font-semibold">Security Overview</h3>
            </div>
            <div className="p-4 space-y-3">
              <div className="flex items-center justify-between px-2 py-1.5">
                <span className="text-sm text-muted-foreground">Active sessions</span>
                <span className="text-sm font-medium">{sessions.length}</span>
              </div>
              <div className="flex items-center justify-between px-2 py-1.5">
                <span className="text-sm text-muted-foreground">Pending resets</span>
                <span className="text-sm font-medium">{passwordResets.length}</span>
              </div>
              <div className="flex items-center justify-between px-2 py-1.5">
                <span className="text-sm text-muted-foreground">2FA</span>
                <span className="text-sm font-medium text-amber-600">Not enabled</span>
              </div>
              <div className="flex items-center justify-between px-2 py-1.5">
                <span className="text-sm text-muted-foreground">Last login</span>
                <span className="text-sm font-medium">{user.lastLoginAt ? formatDate(user.lastLoginAt) : 'Never'}</span>
              </div>
            </div>
          </div>

          <Button variant="outline" className="w-full" render={<Link href="/profile/sessions" />}>
            <Clock className="size-4" /> Manage sessions
          </Button>
        </div>
      </div>
    </div>
  )
}
